version: '1'

services:
  api-db:
    image: postgres
    container_name: "proxy_db"
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./start.sql:/docker-entrypoint-initdb.d/init_api_db.sql
    ports:
      - "5432:5432"
  api-server:
    build: .
    container_name: "proxy"
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"